### ISSUE TITLE
 Some options do not work

### ISSUE THREAD

**Issue by GabrieSouza** [ImDR/masy-gallery#1]
Options rowHeight and lastRow are not working.

**Comment by ImDR** [comment]
show me the shortcode

**Comment by GabrieSouza** [comment]
It's the shortcode: [justified-gallery id='113' rowHeight='300' lastRow='center' ]

**Comment by ImDR** [comment]
This issue has been fixed. Download latest version of the plugin: https://wordpress.org/plugins/masy-gallery/

**Comment by GabrieSouza** [comment]
It's work. Thank you!
